import localFont from "next/font/local";
import "./globals.css";
import {IoImageOutline} from "react-icons/io5";
import { FaMeta } from "react-icons/fa6";
import { FaFan } from "react-icons/fa6";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100%] w-[100%] min-h-[100vh]`}
      >
        <div className="h-[5rem] w-[100%] bg-black ">
        </div>
        <div className="flex h-[calc(100%-5rem)] min-h-[calc(100vh-5rem)]">
          <div className="w-[5rem] pt-[3rem] bg-black flex flex-col justify-start items-center gap-10">
            <FaFan size={30} color="green"/>
            <IoImageOutline size={30} color="white"/>
            <FaMeta size={30} color="white"/>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
